#!/bin/bash
#echo "txn_cnt"
grep "\[summary\]" $1 | grep -oP "(?<= txn_cnt=)[0-9]*.[0-9]*"
#echo "abort_cnt"
grep "\[summary\]" $1 | grep -oP "(?<= abort_cnt=)[0-9]*.[0-9]*"
#echo "throughput"
grep "\[summary\]" $1 | grep -oP "(?<= throughput=)[0-9]*.[0-9]*"
#echo "runtime"
grep -oP "(?<=Total Runtime : )[0-9]*.[0-9]*" $1
#echo "time_index"
grep "\[summary\]" $1 | grep -oP "(?<= time_index=)[0-9]*.[0-9]*"
#echo "time_man"
grep "\[summary\]" $1 | grep -oP "(?<= time_man=)[0-9]*.[0-9]*"
#echo "time_abort"
grep "\[summary\]" $1 | grep -oP "(?<= time_abort=)[0-9]*.[0-9]*"
#echo "time_cleanup"
grep "\[summary\]" $1 | grep -oP "(?<= time_cleanup=)[0-9]*.[0-9]*"
#echo "total_time"
grep "\[summary\]" $1 | grep -oP "(?<= run_time=)[0-9]*.[0-9]*"
